# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
 container-job:
    # Containers must run in Linux based operating systems
    runs-on: ubuntu-latest
  
    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]

    # Service containers to run with `container-job`
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres
        # Provide the password for postgres
        env:
          POSTGRES_PASSWORD: rootUser
          POSTGRES_USER: dev
          POSTGRES_DB : ecom
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      # Downloads a copy of the code in your repository before running CI tests
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - name: Connect to PostgreSQL and make migrations
        # Runs a script that creates a PostgreSQL client, populates
        # the client with tables
        run: make migrations 
      - name: populate the test database with test database
        run: make seed
        # Environment variable used by the `client.js` script to create a new PostgreSQL client.
        # - run: npm run build --if-present
      - run: npm test
        env:
          # The hostname used to communicate with the PostgreSQL service container
          POSTGRES_HOST: postgres
          POSTGRES_PASSWORD: rootUser
          POSTGRES_USER: dev
          POSTGRES_DB : ecom
          # The default PostgreSQL port
          POSTGRES_PORT: 5432
          JWT_SECRET : keyboard_cat


